import Head from 'next/head'

import { Container } from '../styles/pages/Home'
import FeaturedCarousel from '../components/FeaturedCarousel'

const About = () => {
  return (
    <Container className="container mx-auto my-0 h-screen">
      <Head>
        <title>NoBareFeet - About</title>
        <meta name="description" content="Generated by create next app" />
      </Head>
      <div className="pt-14">
        <FeaturedCarousel />
      </div>
    </Container>
  )
}

export default About
