import Head from 'next/head'
import nobarefeetImg from '../assets/barefeet.jpg'

import { Container } from '../styles/pages/Home'

const About = () => {
  return (
    <Container>
      <Head>
        <title>NoBareFeet - About</title>
        <meta name="description" content="Generated by create next app" />
      </Head>
      <div>
        <img src={nobarefeetImg.src} alt="" />
        <h1>Hello NoBareFeet! About US</h1>
      </div>
    </Container>
  )
}

export default About
