import Head from 'next/head'
import nobarefeetImg from '../assets/barefeet.jpg'
import Product from '../components/Product'
import { Container } from '../styles/pages/Home'

const Home = () => {
  return (
    <Container className="container my-0 mx-auto  h-screen flex-col ">
      <Head>
        <title>NoBareFeet - Homepage</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="flex items-center justify-center">
        <img src={nobarefeetImg.src} alt="" />
        <h1 className="text-center">Hello NoBareFeet!</h1>
      </div>
      <Product />
    </Container>
  )
}

export default Home
