import Head from 'next/head'
import nobarefeetImg from '../assets/google.svg'
import { Container } from '../styles/pages/Home'

function Login() {
  return (
    <Container className="my-0 mx-auto flex h-screen flex-col items-center justify-center">
      <Head>
        <title>NoBareFeet - Register</title>
        <meta name="description" content="Generated by create next app" />
      </Head>
      <div>
        <div className="flex h-[600px] w-[424px] flex-col justify-between rounded-lg bg-gray-300 p-8">
          <div className="">
            <input
              type="email"
              name=""
              id=""
              className="@apply input-register"
              placeholder="Email"
            />
            <input
              type="password"
              name=""
              id=""
              className="@apply input-register"
              placeholder="Senha"
            />
          </div>

          <div className="">
            <input
              type="submit"
              value="Entrar"
              className="hover: mb-4 h-10 w-[360px] cursor-pointer bg-white hover:bg-gray-700 hover:text-white"
            />

            <input
              type="submit"
              value="Entrar com Google"
              className="hover: mb-4 h-10 w-[360px] cursor-pointer bg-white hover:bg-gray-700  hover:text-white"
            />

            <div className="m-2 flex h-10 justify-center">
              <p>Ou</p>
            </div>

            <input
              type="submit"
              value="Registrar"
              className="hover: h-10 w-[360px] cursor-pointer bg-white hover:bg-gray-700 hover:text-white"
            />
          </div>
        </div>
      </div>
    </Container>
  )
}

export default Login
