import Head from 'next/head'
import nobarefeetImg from '../assets/barefeet.jpg'
import { Container } from '../styles/pages/Home'

const Register = () => {
  return (
    <Container className="my-0 mx-auto flex h-screen flex-col items-center justify-center">
      <Head>
        <title>NoBareFeet - Register</title>
        <meta name="description" content="Generated by create next app" />
      </Head>
      <div>
        <div className="flex h-[600px] w-[424px] flex-col justify-between rounded-lg bg-gray-300 p-8">
          <div className="">
            <input
              type="text"
              name=""
              id=""
              className="@apply input-register"
              placeholder="Nome Completo"
            />
            <input
              type="text"
              name=""
              id=""
              className="@apply input-register"
              placeholder="CPF"
            />
            <input
              type="email"
              name=""
              id=""
              className="@apply input-register"
              placeholder="Email"
            />
            <input
              type="password"
              name=""
              id=""
              className="@apply input-register"
              placeholder="Senha"
            />
            <input
              type="password"
              name=""
              id=""
              className="@apply input-register"
              placeholder="Repetir senha"
            />
          </div>

          <div>
            <input
              type="submit"
              value="Registrar"
              className="hover: h-10 w-[360px] cursor-pointer bg-white hover:bg-gray-700 hover:text-white"
            />
          </div>
        </div>
      </div>
    </Container>
  )
}

export default Register
