import Head from "next/head"

const Home = () => {
  return (
    <div>
      <Head>
        <title>NoBareFeet</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <h1>Hello NoBareFeet!</h1>
      </main>
    </div>
  )
}

export default Home
